
spring:
  application:
    name: authorization-resource

  profiles:
    active: dev

  security:
    oauth2:
      jwt:
        signingKey: oauth

  cloud:
    nacos:
      discovery:
        server-addr: ${REGISTER_HOST:localhost}:${REGISTER_PORT:8848}
      config:
        server-addr: ${REGISTER_HOST:localhost}:${REGISTER_PORT:8848}
        file-extension: yml


