spring:
  application:
    name: gateway
    profiles: dev

  #cloud:
    #nacos:
      #config:
        #server-addr: ${REGISTER_HOST:localhost}:${REGISTER_PORT:8848}
        #file-extension: yml

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 配置详解：
        #id: 在所有路由定义中需要唯一，不能重复
        #uri: lb://** lb://为固定写法，表示开启负载均衡； ** 即服务在Nacos中注册的名字
        #predicates:- Path=/product/** 使用"Path Route Predicate Factory"，规则为/product/** 的请求都还转发至微服务product-service中。
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: sysadmin
          uri: lb://sysadmin
          predicates:
            - Path=/admin/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**


