spring:
  application:
    name: gateway
    profiles: dev

  #cloud:
    #nacos:
      #config:
        #server-addr: ${REGISTER_HOST:localhost}:${REGISTER_PORT:8848}
        #file-extension: yml

    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        # 配置详解：
        #id: 在所有路由定义中需要唯一，不能重复
        #uri: lb://** lb://为固定写法，表示开启负载均衡； ** 即服务在Nacos中注册的名字
        #predicates:- Path=/product/** 使用"Path Route Predicate Factory"，规则为/product/** 的请求都还转发至微服务product-service中。
        - id: member
          uri: lb://member # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在nacos上的服务名
          predicates:
            - Path=/hello/**
            - Method=GET,POST
        - id: sysadmin
          uri: lb://sysadmin
          predicates:
            - Method=GET,POST
            - Path=/user/**
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1


