server:
  port: 6668

spring:
  datasource:
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/microservice?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:jfm}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        clientId: user-client
        clientSecret: user-secret-8888
        accessTokenValiditySeconds: 20000
        refreshTokenValiditySeconds: 20000
        user-authorization-uri: http://localhost:6667/oauth/authorize
        grant_type: password
        scope: all
        access-token-uri: http://localhost:6667/oauth/token
      resource:
        token-info-uri: http://localhost:6667/oauth/check_token
        user-info-uri: http://localhost:6667/user
        jwt:
          key-uri: http://localhost:6667/oauth/token_key
          key-value: oauth
    # rabbitmq
    rabbitmq:
      host: ${RABBIT_MQ_USERNAME:guest}
      username: ${RABBITMQ_USERNAME:guest}
      password: ${RABBIT_MQ_PASSWORD:guest}
      port: ${RABBITMQ_MQ_PORT:5672}

    # redis
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:jfm}



      ##忽略认证的地址






