
### goone config ###

server:
  port: 4444

spring:
  jackson:
    date-format: YYYY-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://192.168.1.246:4306/go-one?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver







