
### goone config ###

server:
  port: 8003

spring:
  jackson:
    date-format: YYYY-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/microservice?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: xyGames
    driverClassName: com.mysql.jdbc.Driver










