server:
  port: 6676

spring:
  datasource:
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/microservice?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.jdbc.Driver

  security:
    oauth2:
      client:
        clientId: user-client
        clientSecret: user-secret-8888
        accessTokenValiditySeconds: 20000
        refreshTokenValiditySeconds: 20000
        user-authorization-uri: http://localhost:6667/oauth/authorize
        access-token-uri: http://localhost:6667/oauth/token
      resource:
        jwt:
          key-uri: http://localhost:6667/oauth/token_key
          key-value: oauth


