spring:
  profiles:
    active: dev

  application:
    name: authorization-server

    security:
      oauth2:
        resource:
          user-info-uri: http://localhost:6002/user/current/get
          id: account-service

# 集成了资源服务
# 直接放行URL
ignore:
  urls:
    - /index.html
    - /static/**
    - /authentication/form
    - /authentication/require
    - /oauth/**
    - /actuator/**
    - /druid/*

  cloud:
    nacos:
      discovery:
        server-addr: ${REGISTER_HOST:localhost}:${REGISTER_PORT:8848}
      config:
        server-addr: ${REGISTER_HOST:localhost}:${REGISTER_PORT:8848}
        file-extension: yml
