
### goone config ###

server:
  port: 4444

spring:
  jackson:
    date-format: YYYY-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:192.168.1.246}:${DATASOURCE_PORT:4306}/go-one?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver







