server:
  port: 8002

spring:
  datasource:
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/microservice?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
    #url: jdbc:mysql://localhost:3306/microservice?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver


  security:
    oauth2:
      resource:
        user-info-uri: http://localhost:6667/user/current/get
        id: sysadmin

        #client:
        #clientId: user-client
        #clientSecret: user-secret-8888
        #access-token-uri: http://localhost:6667/oauth/token


