server:
  port: 8012

spring:
  datasource:
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/microservice?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:jfm}
    #url: jdbc:mysql://localhost:3306/microservice?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池
    hikari:
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      poolName: DatebookHikariCP
      maxLifetime: 1800000
      connectionTestquery: SELECT 1


  security:
    oauth2:
      resource:
        user-info-uri: http://localhost:6667/user
        id: sysadmin

      client:
        clientId: user-client
        clientSecret: user-secret-8888
        access-token-uri: http://localhost:6667/oauth/token
        grant-type: client_credentials,password
        scope: all

        #client:
        #clientId: user-client
        #clientSecret: user-secret-8888
        #access-token-uri: http://localhost:6667/oauth/token


