server:
  port: 8006

spring:
  security:
    oauth2:
      client:
        clientId: user-client
        clientSecret: user-secret-8888
        user-authorization-uri: http://localhost:6667/oauth/authorize
        access-token-uri: http://localhost:6667/oauth/token
      resource:
        jwt:
          key-uri: http://localhost:6667/oauth/token_key
          key-value: oauth

      #resource:
        #id: user-client
        #user-info-uri: user-info
        #authorization:
          #check-token-access: http://localhost:6667/oauth/check_token


