server:
  port: 8883

spring:
  #security:
    #user:
      #name: test
      #password: 123456
    oauth2:
      client:
        clientId: user-client
        clientSecret: user-secret-8888
        user-authorization-uri: http://localhost:6667/oauth/authorize
        access-token-uri: http://localhost:6667/oauth/token
      resource:
        jwt:
          key-uri: http://localhost:6667/oauth/token_key
          key-value: oauth

      #resource:
        #id: user-client
        #user-info-uri: user-info
        #authorization:
          #check-token-access: http://localhost:6667/oauth/check_token
microservice:
  security:
    ignore:
      httpUrls: >
        /user/login,
        /login.html,
        /user/test,
        /v2/api-/**,
        /swagger-resources/configuration/ui,
        /swagger-resources,
        /swagger-resources/configuration/security，
        /swagger-ui.html

      auth:
        # 配置必需认证的url
        httpUrls: /api-uaa/clients/**
        #是否开启url级别权限
        urlEnabled: false

