microservice:
  oauth2:
    token:
      store:
        type: authJwt
  swagger:
    enabled: true
    title: 认证中心
    description: 认证中心接口文档
    version: 1.0
    base-package: com.central.oauth.controller
  security:
    ignore:
      # 忽略认证的地址
      httpUrls: >
        /validata/**,
        /clients,
        /clients/**,
        /login.html,
        /css/**,
        /images/**,
        /js/**
    code:
      # 忽略验证码的应用编号
      ignoreClientCode: app

jwt:
  expiration: 604800
  secret: mySecret
  tokenHead: 'Bearer'
  tokenHeader: Authorization